/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NftOwner struct {
	// The address of the contract of the NFT
	TokenAddress string `json:"token_address"`
	// The token id of the NFT
	TokenId string `json:"token_id"`
	// The type of NFT contract standard
	ContractType string `json:"contract_type"`
	// The address of the owner of the NFT
	OwnerOf string `json:"owner_of"`
	// The blocknumber when the amount or owner changed
	BlockNumber string `json:"block_number"`
	// The blocknumber when the NFT was minted
	BlockNumberMinted string `json:"block_number_minted"`
	// The uri to the metadata of the token
	TokenUri string `json:"token_uri,omitempty"`
	// The metadata of the token
	Metadata string `json:"metadata,omitempty"`
	// when the metadata was last updated
	SyncedAt string `json:"synced_at,omitempty"`
	// The number of this item the user owns (used by ERC1155)
	Amount string `json:"amount,omitempty"`
	// The name of the Token contract
	Name string `json:"name"`
	// The symbol of the NFT contract
	Symbol string `json:"symbol"`
}
