/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IpfsFileRequest struct {
	// Path to file
	Path string `json:"path"`
	// base64 or JSON
	Content string `json:"content"`
}
