/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Erc721Metadata struct {
	// The name of the token Contract
	Name string `json:"name"`
	// The symbol of the NFT contract
	Symbol string `json:"symbol"`
	TokenUri string `json:"token_uri,omitempty"`
}
