/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NftTransfer struct {
	// The address of the contract of the NFT
	TokenAddress string `json:"token_address"`
	// The token id of the NFT
	TokenId string `json:"token_id"`
	// The address that sent the NFT
	FromAddress string `json:"from_address,omitempty"`
	// The address that recieved the NFT
	ToAddress string `json:"to_address"`
	// The value that was sent in the transaction (ETH/BNB/etc..)
	Value string `json:"value,omitempty"`
	// The number of tokens transferred
	Amount string `json:"amount,omitempty"`
	// The type of NFT contract standard
	ContractType string `json:"contract_type"`
	// The blocknumber of the transaction
	BlockNumber string `json:"block_number"`
	// The block timestamp
	BlockTimestamp string `json:"block_timestamp"`
	// The block hash of the transaction
	BlockHash string `json:"block_hash"`
	// The transaction hash
	TransactionHash string `json:"transaction_hash"`
	// The transaction type
	TransactionType string `json:"transaction_type,omitempty"`
	// The transaction index
	TransactionIndex string `json:"transaction_index,omitempty"`
	// The log index
	LogIndex int32 `json:"log_index"`
	// The operator present only for ERC1155 Transfers
	Operator string `json:"operator,omitempty"`
}
