/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ChainList string

// List of chainList
const (
	ETH_ChainList ChainList = "eth"
	0X1__ChainList ChainList = "0x1"
	ROPSTEN_ChainList ChainList = "ropsten"
	0X3__ChainList ChainList = "0x3"
	RINKEBY_ChainList ChainList = "rinkeby"
	0X4__ChainList ChainList = "0x4"
	GOERLI_ChainList ChainList = "goerli"
	0X5__ChainList ChainList = "0x5"
	KOVAN_ChainList ChainList = "kovan"
	0X2A__ChainList ChainList = "0x2a"
	POLYGON_ChainList ChainList = "polygon"
	0X89__ChainList ChainList = "0x89"
	MUMBAI_ChainList ChainList = "mumbai"
	0X13881__ChainList ChainList = "0x13881"
	BSC_ChainList ChainList = "bsc"
	0X38__ChainList ChainList = "0x38"
	BSC_TESTNET_ChainList ChainList = "bsc testnet"
	0X61__ChainList ChainList = "0x61"
	AVALANCHE_ChainList ChainList = "avalanche"
	0XA86A__ChainList ChainList = "0xa86a"
	AVALANCHE_TESTNET_ChainList ChainList = "avalanche testnet"
	0XA869__ChainList ChainList = "0xa869"
	FANTOM_ChainList ChainList = "fantom"
	0XFA__ChainList ChainList = "0xfa"
)
