/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ReservesCollection struct {
	// reserve0
	Reserve0 string `json:"reserve0"`
	// reserve1
	Reserve1 string `json:"reserve1"`
}
