/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BlockDate struct {
	// The date of the block
	Date string `json:"date"`
	// The blocknumber
	Block float64 `json:"block"`
	// The timestamp of the block
	Timestamp float64 `json:"timestamp"`
}
