/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RunContractDto struct {
	// The contract abi
	Abi *interface{} `json:"abi"`
	// The params for the given function
	Params *interface{} `json:"params,omitempty"`
}
