/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Log struct {

	LogIndex string `json:"log_index"`
	// The hash of the transaction
	TransactionHash string `json:"transaction_hash"`

	TransactionIndex string `json:"transaction_index"`
	// The address of the contract
	Address string `json:"address"`
	// The data of the log
	Data string `json:"data"`

	Topic0 string `json:"topic0"`

	Topic1 string `json:"topic1,omitempty"`

	Topic2 string `json:"topic2,omitempty"`

	Topic3 string `json:"topic3,omitempty"`
	// The timestamp of the block
	BlockTimestamp string `json:"block_timestamp"`
	// The block number
	BlockNumber string `json:"block_number"`
	// The hash of the block
	BlockHash string `json:"block_hash"`
}
