/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Transaction struct {
	// The hash of the transaction
	Hash string `json:"hash"`
	// The nonce of the transaction
	Nonce string `json:"nonce"`
	// The transaction index
	TransactionIndex string `json:"transaction_index"`
	// The sender
	FromAddress string `json:"from_address"`
	// The recipient
	ToAddress string `json:"to_address"`
	// The value that was transfered (in wei)
	Value string `json:"value"`
	// The gas of the transaction
	Gas string `json:"gas"`
	// The gas price
	GasPrice string `json:"gas_price"`
	// The input
	Input string `json:"input"`
	// The receipt cumulative gas used
	ReceiptCumulativeGasUsed string `json:"receipt_cumulative_gas_used"`
	// The receipt gas used
	ReceiptGasUsed string `json:"receipt_gas_used"`
	// The receipt contract address
	ReceiptContractAddress string `json:"receipt_contract_address"`
	// The receipt root
	ReceiptRoot string `json:"receipt_root"`
	// The receipt status
	ReceiptStatus string `json:"receipt_status"`
	// The block timestamp
	BlockTimestamp string `json:"block_timestamp"`
	// The block number
	BlockNumber string `json:"block_number"`
	// The block hash
	BlockHash string `json:"block_hash"`
}
