/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type chainList string

// List of chainList
const (
	ETH ChainList = "eth"
	0X1_ ChainList = "0x1"
	ROPSTEN ChainList = "ropsten"
	0X3_ ChainList = "0x3"
	RINKEBY ChainList = "rinkeby"
	0X4_ ChainList = "0x4"
	GOERLI ChainList = "goerli"
	0X5_ ChainList = "0x5"
	KOVAN ChainList = "kovan"
	0X2A_ ChainList = "0x2a"
	POLYGON ChainList = "polygon"
	0X89_ ChainList = "0x89"
	MUMBAI ChainList = "mumbai"
	0X13881_ ChainList = "0x13881"
	BSC ChainList = "bsc"
	0X38_ ChainList = "0x38"
	BSC_TESTNET ChainList = "bsc testnet"
	0X61_ ChainList = "0x61"
	AVALANCHE ChainList = "avalanche"
	0XA86A_ ChainList = "0xa86a"
	AVALANCHE_TESTNET ChainList = "avalanche testnet"
	0XA869_ ChainList = "0xa869"
	FANTOM ChainList = "fantom"
	0XFA_ ChainList = "0xfa"
)
