/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NativeErc20Price struct {
	// The native price of the token
	Value string `json:"value"`
	// The number of decimals of the token
	Decimals int32 `json:"decimals"`
	// The Name of the token
	Name string `json:"name"`
	// The Symbol of the token
	Symbol string `json:"symbol"`
}
