/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NftMetadata struct {
	// The address of the contract of the NFT
	TokenAddress string `json:"token_address"`
	// The token id of the NFT
	TokenId string `json:"token_id"`
	// The type of NFT contract standard
	ContractType string `json:"contract_type"`
	// The uri to the metadata of the token
	TokenUri string `json:"token_uri"`
	// The metadata of the token
	Metadata string `json:"metadata"`
	// when the metadata was last updated
	SyncedAt string `json:"synced_at"`
}
