/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Block struct {
	// The block timestamp
	Timestamp string `json:"timestamp"`
	// The block number
	Number string `json:"number"`
	// The block hash
	Hash string `json:"hash"`
	// The block hash of the parent block
	ParentHash string `json:"parent_hash"`
	// The nonce
	Nonce string `json:"nonce"`

	Sha3Uncles string `json:"sha3_uncles"`

	LogsBloom string `json:"logs_bloom"`

	TransactionsRoot string `json:"transactions_root"`

	StateRoot string `json:"state_root"`

	ReceiptsRoot string `json:"receipts_root"`
	// The address of the miner
	Miner string `json:"miner"`
	// The difficulty of the block
	Difficulty string `json:"difficulty"`
	// The total difficulty
	TotalDifficulty string `json:"total_difficulty"`
	// The block size
	Size string `json:"size"`

	ExtraData string `json:"extra_data"`
	// The gas limit
	GasLimit string `json:"gas_limit"`
	// The gas used
	GasUsed string `json:"gas_used"`
	// The number of transactions in the block
	TransactionCount string `json:"transaction_count"`
	// The transactions in the block
	Transactions []BlockTransaction `json:"transactions"`
}
