/*
 * Moralis API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NftContractMetadataCollection struct {
	// The total number of matches for this query
	Total int32 `json:"total"`
	// The page of the current result
	Page int32 `json:"page"`
	// The number of results per page
	PageSize int32 `json:"page_size"`

	Result []NftContractMetadata `json:"result"`
}
